products:
  build: .
  dockerfile: docker-products-app.dockerfile
  container_name: nmlsample_products
  ports:
    - "5091:5090"
    
stores:
  build: .
  dockerfile: docker-stores-app.dockerfile
  container_name: nmlsample_stores
  ports:
    - "5092:5090"

nginx:
  build: .
  dockerfile: docker-nginx.dockerfile
  container_name: nmlsample_nginx
  ports:
    - "5000:80"
  links:
    - products
    - stores
